### ISSUE TITLE
Fake issue

### ISSUE THREAD

**Issue by astrofrog** [astrofrog/test-bot#1]

**Comment by astrofrog** [comment]
@pllim - 🎉

**Comment by astrofrog** [comment]
Just testing that I get a warning if I turn off issue closing

**Comment by pllim** [comment]
Yay!

**Comment by astrofrog** [comment]
Internet high-five! Thanks for all your help!

**Comment by pllim** [comment]
I didn't really help much but I sure did learn a lot. Thank YOU!
